FROM node:14 as build
WORKDIR /srv

COPY ./web/. ./web/
COPY ./infra/. ./infra/

RUN cd web && \
    echo "Installing packages... $(NODE_ENV=development yarn install)" && \
    echo "Building web...  $(NODE_ENV=production yarn build)"

FROM nginx:1.22 as infra
WORKDIR /srv
RUN apt-get update -qq -o=Dpkg::Use-Pty=0 && apt-get install netcat -yqq -o=Dpkg::Use-Pty=0

COPY --from=build /srv/infra/web/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /srv/infra/web/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /srv/infra/web/nginx/conf.d/* /etc/nginx/conf.d/
COPY --from=build /srv/infra/web/entrypoint.sh /entrypoint.sh

FROM infra as nginx
COPY --from=build /srv/web /srv/web

RUN ["chmod", "+x", "/entrypoint.sh"]

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
